app:
  build: .
  volumes:
    - ./src:/var/www/html
  ports:
    - "8080:80"
    - "8443:443"
  links:
    - postgres
    - redis
postgres:
  image: postgres
  ports:
    - "5432:5432"
redis:
  image: redis
  ports:
    - "6379:6379"
